### ISSUE TITLE
Fix and improve extract_course_data 

### ISSUE THREAD

**Issue by PremBharwani** [PremBharwani/clash-hai-bhai#11]
@theslyther-in 

When you run the script `scrape_csv.py`, you would encounter the error:
```
$ python .\scrape_csv.py
Traceback (most recent call last):
  File "C:\clash-hai-bhai\extract_course_data\scrape_csv.py", line 6, in <module>
    import fix
  File "C:\clash-hai-bhai\extract_course_data\fix.py", line 8, in <module>
    f = open(filename, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'output.json'
```

Could you please work on the following:
* Fix the bug I have mentioned above
* Currently the files are pretty much scattered and it is hard to understand the purpose they serve. Could you please restructure the code into modular functions & just move all the utility functions into one file itself. There are unnecessary files, please get rid of them.

**Comment by juggernautjha** [comment]
fixed :)
